### ISSUE TITLE
Chybějící názvy u zápisků

### ISSUE THREAD

**Issue by Sebight** [M4TY/zapisky#50]
Ne každý ze zápisků má název v .md souboru. 

Toto může zapříčinit zmatení, když mám nějaký soubor otevřený.

**Comment by M4TY** [comment]
Asi nechápu pointu issue? Příklad?

**Comment by Sebight** [comment]
https://materialy.matyashimmer.eu/note?link=https://raw.githubusercontent.com/M4TY/zapisky/main/Čeština/Němcová.html

Nijak nelze poznat co právě procházím

**Comment by M4TY** [comment]
Toto je issue směřující na [web](https://github.com/M4TY/materialy-web/issues/new/choose), ne na zápisky.

**Comment by M4TY** [comment]
Toto je chyba která se dá vyřešit v rámci zápisků, tudíž issue na web není potřeba. Lze vytvořit pull request s opravou. Stačí na začátek každého md souboru přidat 
# Téma
